class Comment {
  final String creator;
  final String type;
  final String text;
  final String imgUrl;


  const Comment({
  required this.creator,
  required this.type,
  required this.text,
  required this.imgUrl,});
}

const allComments =[
  Comment(creator: "pct", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "pct", type: "text", text: "Hello this is my dog asdn dansdh  sadhas hdmsd asdnaslkdhas ds dashdsnddalddha hashdasn  sodhoasd ladhoaisdn as dolishdand dasldhj   dadkhs  ", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "worse", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "worse", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "worse", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "wll", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "admin", type: "text", text: "Well is quite cute", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "thanks", imgUrl: ""),
  Comment(creator: "admin", type: "image", text: "", imgUrl: "https://i.insider.com/5484d9d1eab8ea3017b17e29?width=600&format=jpeg&auto=webp"),
  Comment(creator: "admin", type: "text", text: "how about my cat", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "nice", imgUrl: ""),
  Comment(creator: "pct", type: "text", text: "adsdas", imgUrl: ""),
];